#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
fi

case "$1" in
    purge)
        # remove the index on purge only
        rm -rf /var/lib/dux
        ;;
esac

exit 0
