#!/bin/sh
set -e

case "$1" in
    remove|deconfigure|upgrade)
        if [ -d /run/systemd/system ]; then
            systemctl stop dux.service || true
            systemctl disable dux.service || true
        fi
        ;;
esac

exit 0
